### ISSUE TITLE
npm ERR! Invalid version: "1.0"

### ISSUE THREAD

**Issue by malcolmlewis** [openSUSE/fuel-ignition#3]
Hi
I'm getting the following error when trying to run;

```
podman run --network=host fuelignition:latest
npm ERR! Invalid version: "1.0"

npm ERR! A complete log of this run can be found in:
npm ERR!     /fuelignition/.npm/_logs/2022-05-23T13_54_50_536Z-debug.log
```

Operating System: openSUSE Tumbleweed 20220521

I've attached the debug log and make output;

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node14', '/usr/bin/npm14', 'run', 'dev' ]
2 info using npm@6.14.15
3 info using node@v14.18.3
4 verbose config Skipping project config: /fuelignition/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid version: "1.0"
5 verbose stack     at Object.fixVersionField (/usr/lib64/node_modules/npm14/node_modules/normalize-package-data/lib/fixer.js:191:13)
5 verbose stack     at /usr/lib64/node_modules/npm14/node_modules/normalize-package-data/lib/normalize.js:32:38
5 verbose stack     at Array.forEach (<anonymous>)
5 verbose stack     at normalize (/usr/lib64/node_modules/npm14/node_modules/normalize-package-data/lib/normalize.js:31:15)
5 verbose stack     at final (/usr/lib64/node_modules/npm14/node_modules/read-package-json/read-json.js:429:5)
5 verbose stack     at then (/usr/lib64/node_modules/npm14/node_modules/read-package-json/read-json.js:161:5)
5 verbose stack     at /usr/lib64/node_modules/npm14/node_modules/read-package-json/read-json.js:382:12
5 verbose stack     at /usr/lib64/node_modules/npm14/node_modules/graceful-fs/graceful-fs.js:123:16
5 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:71:3)
6 verbose cwd /fuelignition
7 verbose Linux 5.17.9-1-default
8 verbose argv "/usr/bin/node14" "/usr/bin/npm14" "run" "dev"
9 verbose node v14.18.3
10 verbose npm  v6.14.15
11 error Invalid version: "1.0"
12 verbose exit [ 1, true ]
```

```
make
podman build --build-arg CONTAINER_USERID=1000 -t fuelignition .
STEP 1/10: FROM registry.suse.com/bci/nodejs
Trying to pull registry.suse.com/bci/nodejs:latest...
Getting image source signatures
Copying blob b03c0b85d07c done  
Copying blob 669090d919f8 done  
Copying config d85454d264 done  
Writing manifest to image destination
Storing signatures
STEP 2/10: ARG CONTAINER_USERID
--> c2baf60777c
STEP 3/10: RUN zypper -n install --no-recommends mkisofs
Refreshing service 'container-suseconnect-zypp'.
Problem retrieving the repository index file for service 'container-suseconnect-zypp':
[container-suseconnect-zypp|file:/usr/lib/zypp/plugins/services/container-suseconnect-zypp] 
Warning: Skipping service 'container-suseconnect-zypp' because of the above error.
Building repository 'SLE_BCI' cache [....done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  libscg1_0 libschily1_0 mkisofs zisofs-tools

The following 4 packages are not supported by their vendor:
  libscg1_0 libschily1_0 mkisofs zisofs-tools

4 new packages to install.
Overall download size: 478.4 KiB. Already cached: 0 B. After the operation, additional 1.7 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libschily1_0-3.02~a09-4.6.1.x86_64 (1/4),  62.0 KiB (140.8 KiB unpacked)
Retrieving: libschily1_0-3.02~a09-4.6.1.x86_64.rpm [done]
Retrieving package libscg1_0-3.02~a09-4.6.1.x86_64 (2/4),  45.0 KiB (104.4 KiB unpacked)
Retrieving: libscg1_0-3.02~a09-4.6.1.x86_64.rpm [done]
Retrieving package mkisofs-3.02~a09-4.6.1.x86_64 (3/4), 342.7 KiB (  1.4 MiB unpacked)
Retrieving: mkisofs-3.02~a09-4.6.1.x86_64.rpm [.done (304.0 KiB/s)]
Retrieving package zisofs-tools-1.0.8-1.27.x86_64 (4/4),  28.7 KiB ( 52.9 KiB unpacked)
Retrieving: zisofs-tools-1.0.8-1.27.x86_64.rpm [done]

Checking for file conflicts: [.......done]
(1/4) Installing: libschily1_0-3.02~a09-4.6.1.x86_64 [.......done]
(2/4) Installing: libscg1_0-3.02~a09-4.6.1.x86_64 [......done]
(3/4) Installing: mkisofs-3.02~a09-4.6.1.x86_64 [............done]
(4/4) Installing: zisofs-tools-1.0.8-1.27.x86_64 [......done]
--> 173bd72f33f
STEP 4/10: RUN useradd -m -d /fuelignition fuelignition -u ${CONTAINER_USERID}
Group 'mail' not found. Creating the user mailbox file with 0600 mode.
--> 0c1820a2c8c
STEP 5/10: ADD . /fuelignition/
--> 1dc4efd1941
STEP 6/10: RUN chown -R fuelignition /fuelignition
--> 98418b4a78b
STEP 7/10: USER fuelignition
--> 88537622831
STEP 8/10: WORKDIR /fuelignition
--> fe0b4463ba6
STEP 9/10: RUN npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN Invalid version: "1.0"
npm WARN fuelignition No description
npm WARN fuelignition No repository field.
npm WARN fuelignition No README data
npm WARN fuelignition No license field.

up to date in 1.14s
found 0 vulnerabilities

--> cdf3b5d9cdf
STEP 10/10: CMD ["npm", "run", "dev"]
COMMIT fuelignition
--> 824585158c5
Successfully tagged localhost/fuelignition:latest
824585158c5ff35c7e9bd902b45bc0cc52424502582f501956ed5d9939335529
```

**Comment by faeller** [comment]
thank you for reporting, I fixed this in https://github.com/openSUSE/fuel-ignition/commit/2135d1cf0ecbf4f61de70995bd5a2676439be273

if the problem persists, please feel free to open the issue again. thank you for your interest! cheers :)
